### ISSUE TITLE
Bug in charRNN

### ISSUE THREAD

**Issue by bencrabbe** [bencrabbe/npdependency#15]
Currently the CharRNN ignores unknown characters.
When a word with no known character is processes it generates an empty character tensor causing a crash.
The solution would be to create a special <unk> character rather than skipping it.
applying this solution breaks all the trained models

**Comment by LoicGrobol** [comment]
@bencrabbe I can think of several ways of fixing this:

1. Treat the unknown characters as padding
2. Skip unknown characters in words that also contain known character and treat words with only unknown character as word with a single padding character
3. Add a special unk character
4. Completely change how we input characters, e.g. à la ELMo where words are processed byte-by-bytes from ther utf-8 encoding

Solutions 1. and 2. have the advantage of being backward compatible (as in, the old models will still work and should keep identical or quasi- perfs on their target corpora). Solution 3. would break backward compatibility (the embedding matrix changes dimension) and doesn't make a lot of sense unless we do char dropout as we already do word dropout to train the models to react to unknown chars. Solution 4. is not backward-compatible either and is horrifying from a conceptual point of view but is maybe the more robust to unseen data.

I think 2. would be the best solution here, but you might have another opinion @bencrabbe :-)

**Comment by LoicGrobol** [comment]
Actually I just checked, I think that a side-effect of #14 is that this is now only an issue if there is a position such that all the sentences in the batch have only words consisting only of unknown character at that position (which is of course not so far-fetched with batches of 1 sentence…). Actually due to how we pad, we are in effect doing 2.

**Comment by bencrabbe** [comment]
ok. thanks. I have a one liner fix for applying 2.
I will do that and commit
