### ISSUE TITLE
Large scale parsing I/O streaming

### ISSUE THREAD

**Issue by bencrabbe** [bencrabbe/npdependency#40]
I tested the parser for parsing larger corpora with BERT models.
Two issues arise:
   - 1) BERT is internally limited to process 512 BPE max per sentence. Otherwise crash. we have to limit max sentence length to approx 200 tokens by default when parsing with BERT
   - 2) Reading very large corpora causes a speed + memory blowup (about 12 hours to put the Gutenberg corpus in memory... takes more time than parsing ;). Thus at parsing (and only for prediction) it seems necessary to read batches in streaming mode to avoid the current issue . Streaming at training will mess the training procedure.

**Comment by bencrabbe** [comment]
The current version of the parser still crashes :
`Token indices sequence length is longer than the specified maximum sequence length for this model (574 > 512). Running this sequence through the model will result in indexing errors`
I guess the limit is still too high (quick guess: BERT is limited wrt num  of subwords not wrt tokens)

**Comment by LoicGrobol** [comment]
That's weird, it's normal that it shows the warning but it shouldn't crash. Could you test in a fresh environment with

```console
pip install -U git+https://https://github.com/bencrabbe/npdependency#bert_truncation
hopsparser parse --raw --ignore-unencodable path/to/model path/to/raw/file path/to/output/file.conllu
```

?

**Comment by bencrabbe** [comment]
done from the branch and it still crashes.
As far as I can see from the code in the branch, there is no constraint on sent length in the parse method
at line 860 graph_parser.py

**Comment by LoicGrobol** [comment]
Indeed, but it shouldn't get to this line when `--raw` and  `--ignore-unencodable` are set. Can you share your command and the traceback? (sorry for the trouble)
